### ISSUE TITLE
[Method]MANAGE ROUTER API

### ISSUE THREAD

**Issue by Tim-BinCoding** [pnc-virtual-company/2022-G1-VC2-PART2#28]

**Comment by VANSAOHANG** [comment]
ROUTER AND FUNCTION NAME DOCUMENT
![image](https://user-images.githubusercontent.com/93769042/190104779-07d32143-f7a7-4484-8ab5-9d91ba4cfde2.png)
![image](https://user-images.githubusercontent.com/93769042/190104838-4e80f43c-a240-4847-a584-098c2bdd4a6b.png)
![image](https://user-images.githubusercontent.com/93769042/190104960-b9080cb4-30f6-47ef-83b8-0ebd71e3621a.png)
