### ISSUE TITLE
ALUMNI PROFILE MOCK UP

### ISSUE THREAD

**Issue by Tim-BinCoding** [pnc-virtual-company/2022-G1-VC2-PART2#7]

**Comment by Tim-BinCoding** [comment]
Be able to see nice interface profile alumni

**Comment by TheavyVun** [comment]
![Image](https://user-images.githubusercontent.com/90229379/189903554-b536ccf3-16eb-41d4-8b01-83a898301317.PNG)



![Image](https://user-images.githubusercontent.com/90229379/189903605-1320e5ca-1c7d-480a-93d5-7e098e5ec52e.PNG)
![Image](https://user-images.githubusercontent.com/90229379/189903606-039616c8-2928-4e95-b141-6a05f760f706.PNG)
![Image](https://user-images.githubusercontent.com/90229379/189903608-10264159-2a4a-43d2-8107-75454756b811.PNG)
![Image](https://user-images.githubusercontent.com/90229379/189903607-d739932f-d5d5-42fc-8f45-2b6d21eb2a1a.PNG)
![Image](https://user-images.githubusercontent.com/90229379/189903609-c7d6eb33-4eec-43f6-a263-f692c9dbf176.PNG)
